services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - server/.env
    ports:
      - "8080:8080"
    networks:
      - backend
      - moodle
      - frontend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 1s
      retries: 2
      start_period: 4s
    cpuset: ${CONTAINER_CPU:-0-1}
    mem_limit: ${CONTAINER_MEMORY:-1G}

  mongodb:
    container_name: mongodb 
    image: bitnamilegacy/mongodb:8-noble
    env_file: 
      - server/.env
    command:
      - '--wiredTigerCacheSizeGB=${MONGODB_CACHE_SIZE:-1}'
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
    - "27017:27017"
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 1s
      retries: 2
      start_period: 4s
    cpuset: ${CONTAINER_CPU:-0-1}
    mem_limit: ${CONTAINER_MEMORY:-1G}

  frontend:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - backend
      - frontend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 1s
      retries: 2
      start_period: 4s
    cpuset: ${CONTAINER_CPU:-0-1}
    mem_limit: ${CONTAINER_MEMORY:-1G}

  moodle:
    container_name: moodle
    image: bitnami/moodle:4.0.3
    env_file:
      - server/.env
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - moodle-data:/bitnami/moodle
    restart: unless-stopped
    networks:
      - moodle
    cpuset: ${CONTAINER_CPU:-0-1}
    mem_limit: ${CONTAINER_MEMORY:-1G}

  mariadb:
    container_name: mariadb
    image: mariadb:12.0.2
    networks:
      - moodle
    env_file:
      - server/.env
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
    cpuset: ${CONTAINER_CPU:-0-1}
    mem_limit: ${CONTAINER_MEMORY:-1G}


volumes:
  mongo-data:
  moodle-data:
  mariadb-data:

networks:
  backend:
    driver: bridge
  moodle:
  frontend:

