version: "3.8"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - backend

  mongodb:
    container_name: mongodb 
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file: 
      - .env
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
    - "27017:27017"
    restart: unless-stopped
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend: