openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/statistics/:
    get:
      tags:
      - api
      - statistics
      summary: Get All Sessions
      operationId: get_all_sessions_api_statistics__get
      parameters:
      - name: begin_timestamp
        in: query
        required: false
        schema:
          default: '1970-01-01T00:00:00'
          title: Begin Timestamp
      - name: end_timestamp
        in: query
        required: false
        schema:
          title: End Timestamp
      responses:
        '200':
          description: Get statistics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionData'
                title: Response Get All Sessions Api Statistics  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - api
      - statistics
      summary: Create Session
      operationId: create_session_api_statistics__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionData'
      responses:
        '201':
          description: Add new session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionData'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/statistics/{session_id}:
    get:
      tags:
      - api
      - statistics
      summary: Get Session By Id
      operationId: get_session_by_id_api_statistics__session_id__get
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
          title: Session Id
      responses:
        '200':
          description: Get session statistic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionData'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - api
      - statistics
      summary: Delete Session
      operationId: delete_session_api_statistics__session_id__delete
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
          title: Session Id
      responses:
        '204':
          description: Delete a session statistic
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/user/:
    get:
      tags:
      - api
      - user
      summary: Get All Users
      operationId: get_all_users_api_user__get
      responses:
        '200':
          description: List all users
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
                title: Response Get All Users Api User  Get
    post:
      tags:
      - api
      - user
      summary: Create User
      operationId: create_user_api_user__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: true
      responses:
        '201':
          description: Add new user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/user/{user_id}:
    get:
      tags:
      - api
      - user
      summary: Get User
      operationId: get_user_api_user__user_id__get
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      responses:
        '200':
          description: Retrieve a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - api
      - user
      summary: Update User
      operationId: update_user_api_user__user_id__put
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        '200':
          description: Update user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - api
      - user
      summary: Delete User
      operationId: delete_user_api_user__user_id__delete
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      responses:
        '204':
          description: Delete a user
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/auth/sign-in:
    post:
      tags:
      - api
      - authorization
      summary: Signin
      operationId: signin_api_auth_sign_in_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInData'
        required: true
      responses:
        '200':
          description: User authorization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ActionTypeEnum:
      type: string
      enum:
      - conversation
      - visible
      - hidden
      title: ActionTypeEnum
    CreateSessionData:
      properties:
        student_id:
          type: integer
          title: Student Id
        student:
          type: string
          title: Student
        email:
          type: string
          format: email
          title: Email
        course:
          type: string
          title: Course
        actions:
          items:
            $ref: '#/components/schemas/Payload'
          type: array
          title: Actions
      type: object
      required:
      - student_id
      - student
      - email
      - course
      title: CreateSessionData
      examples:
      - actions:
        - action_type: conversation
          element_name: "\u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C"
          element_type: button
          event_type: mousedown
          page: http://e.moevm.info/some_course
          timestamp: '2024-04-22T22:20:41.666288'
        course: "\u041A\u0443\u0440\u0441 \u043C\u043E\u043B\u043E\u0434\u043E\u0433\
          \u043E \u0431\u043E\u0439\u0446\u0430"
        email: iiivanov@edu.ru
        id: 823642bf-0e6f-40cd-8d45-9537ca7c0e7d
        student: "\u0418\u0432\u0430\u043D\u043E\u0432 \u0418\u0432\u0430\u043D"
        student_id: 1
      - actions:
        - action_type: hidden
          element_name: "\u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C"
          element_type: page
          event_type: visibilitychange
          page: http://e.moevm.info/some_course
          timestamp: '2024-04-22T22:20:41.666288'
        course: "\u041A\u0443\u0440\u0441 \u043C\u043E\u043B\u043E\u0434\u043E\u0433\
          \u043E \u0431\u043E\u0439\u0446\u0430"
        email: iiivanov@edu.ru
        id: c295fcf9-e95e-4ec9-afbb-403e31ee55dc
        student: "\u0418\u0432\u0430\u043D\u043E\u0432 \u0418\u0432\u0430\u043D"
        student_id: 1
      - actions:
        - action_type: visible
          element_name: "\u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C"
          element_type: page
          event_type: visibilitychange
          page: http://e.moevm.info/some_course
          timestamp: '2024-04-22T22:20:41.666288'
        course: "\u041A\u0443\u0440\u0441 \u043C\u043E\u043B\u043E\u0434\u043E\u0433\
          \u043E \u0431\u043E\u0439\u0446\u0430"
        email: iiivanov@edu.ru
        id: 1e592f38-2097-4856-b98f-0f0f5bd26474
        student: "\u0418\u0432\u0430\u043D\u043E\u0432 \u0418\u0432\u0430\u043D"
        student_id: 1
    CreateUser:
      properties:
        name:
          type: string
          title: Name
        surname:
          type: string
          title: Surname
        lastname:
          type: string
          title: Lastname
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
      type: object
      required:
      - name
      - surname
      - lastname
      - email
      - password
      title: CreateUser
      example:
        email: iiivanov@edu.ru
        lastname: "\u0418\u0432\u0430\u043D\u043E\u0432\u0438\u0447"
        name: "\u0418\u0432\u0430\u043D"
        password: sdfsdfwgesdgcx
        surname: "\u0418\u0432\u0430\u043D\u043E\u0432"
    ElementTypeEnum:
      type: string
      enum:
      - button
      - page
      title: ElementTypeEnum
    EventTypeEnum:
      type: string
      enum:
      - mousedown
      - visibilitychange
      - copy
      - paste
      title: EventTypeEnum
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Payload:
      properties:
        timestamp:
          type: string
          format: date-time
          title: Timestamp
        page:
          type: string
          maxLength: 2083
          minLength: 1
          format: uri
          title: Page
        element_type:
          $ref: '#/components/schemas/ElementTypeEnum'
        element_name:
          type: string
          title: Element Name
        action_type:
          $ref: '#/components/schemas/ActionTypeEnum'
        event_type:
          $ref: '#/components/schemas/EventTypeEnum'
      type: object
      required:
      - page
      - element_type
      - element_name
      - action_type
      - event_type
      title: Payload
      examples:
      - action_type: conversation
        element_name: "\u043E\u0442\u043F\u0440\u0430\u0432\u0438\u0442\u044C"
        element_type: button
        event_type: mousedown
        page: https://example.com
        timestamp: '2024-04-22T22:20:41.661296'
      - action_type: hidden
        element_name: "\u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C"
        element_type: page
        event_type: visibilitychange
        page: https://example.com
        timestamp: '2024-04-22T22:20:41.661296'
      - action_type: visible
        element_name: "\u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C"
        element_type: page
        event_type: visibilitychange
        page: https://example.com
        timestamp: '2024-04-22T22:20:41.661296'
    Role:
      type: string
      enum:
      - admin
      - regular
      title: Role
    SessionData:
      properties:
        _id:
          type: string
          title: ' Id'
        student_id:
          type: integer
          title: Student Id
        student:
          type: string
          title: Student
        email:
          type: string
          format: email
          title: Email
        course:
          type: string
          title: Course
        actions:
          items:
            $ref: '#/components/schemas/Payload'
          type: array
          title: Actions
      type: object
      required:
      - student_id
      - student
      - email
      - course
      title: SessionData
      examples:
      - actions:
        - action_type: conversation
          element_name: "\u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C"
          element_type: button
          event_type: mousedown
          page: http://e.moevm.info/some_course
          timestamp: '2024-04-22T22:20:41.663291'
        course: "\u041A\u0443\u0440\u0441 \u043C\u043E\u043B\u043E\u0434\u043E\u0433\
          \u043E \u0431\u043E\u0439\u0446\u0430"
        email: iiivanov@edu.ru
        id: b0fab966-f468-4086-8bc8-6ffd3543f5b6
        student: "\u0418\u0432\u0430\u043D\u043E\u0432 \u0418\u0432\u0430\u043D"
        student_id: 1
      - actions:
        - action_type: hidden
          element_name: "\u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C"
          element_type: button
          event_type: visibilitychange
          page: http://e.moevm.info/some_course
          timestamp: '2024-04-22T22:20:41.663291'
        course: "\u041A\u0443\u0440\u0441 \u043C\u043E\u043B\u043E\u0434\u043E\u0433\
          \u043E \u0431\u043E\u0439\u0446\u0430"
        email: iiivanov@edu.ru
        id: 90890a86-7943-41ff-9daf-2d17e6427b74
        student: "\u0418\u0432\u0430\u043D\u043E\u0432 \u0418\u0432\u0430\u043D"
        student_id: 1
      - actions:
        - action_type: visible
          element_name: "\u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C"
          element_type: page
          event_type: visibilitychange
          page: http://e.moevm.info/some_course
          timestamp: '2024-04-22T22:20:41.663291'
        course: "\u041A\u0443\u0440\u0441 \u043C\u043E\u043B\u043E\u0434\u043E\u0433\
          \u043E \u0431\u043E\u0439\u0446\u0430"
        email: iiivanov@edu.ru
        id: c25b1ee6-9a41-4945-8764-33885aba05a2
        student: "\u0418\u0432\u0430\u043D\u043E\u0432 \u0418\u0432\u0430\u043D"
        student_id: 1
    SignInData:
      properties:
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
      type: object
      required:
      - email
      - password
      title: SignInData
      example:
        email: iiivanov@edu.ru
        password: sdfsdfwgesdgcx
    UpdateUser:
      properties:
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        surname:
          anyOf:
          - type: string
          - type: 'null'
          title: Surname
        lastname:
          anyOf:
          - type: string
          - type: 'null'
          title: Lastname
        email:
          anyOf:
          - type: string
            format: email
          - type: 'null'
          title: Email
        position:
          anyOf:
          - $ref: '#/components/schemas/Role'
          - type: 'null'
        password:
          anyOf:
          - type: string
          - type: 'null'
          title: Password
      type: object
      required:
      - name
      - surname
      - lastname
      - email
      - position
      - password
      title: UpdateUser
      example:
        email: iiivanov@edu.ru
        lastname: "\u0418\u0432\u0430\u043D\u043E\u0432\u0438\u0447"
        name: "\u0418\u0432\u0430\u043D"
        password: sdfsdfwgesdgcx
        position: regular
        surname: "\u0418\u0432\u0430\u043D\u043E\u0432"
    User:
      properties:
        _id:
          type: string
          title: ' Id'
        name:
          type: string
          title: Name
        surname:
          type: string
          title: Surname
        lastname:
          type: string
          title: Lastname
        email:
          type: string
          format: email
          title: Email
        position:
          $ref: '#/components/schemas/Role'
        password:
          type: string
          title: Password
      type: object
      required:
      - name
      - surname
      - lastname
      - email
      - position
      - password
      title: User
      example:
        email: iiivanov@edu.ru
        id: b532b31f-0d6e-4a6e-9327-92b58eff6c0c
        lastname: "\u0418\u0432\u0430\u043D\u043E\u0432\u0438\u0447"
        name: "\u0418\u0432\u0430\u043D"
        password: sdfsdfwgesdgcx
        position: regular
        surname: "\u0418\u0432\u0430\u043D\u043E\u0432"
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
