version: "3.8"

services:
  mongodb:
    container_name: mongodb 
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file: 
      - .env
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
    - "27017:27017"
    restart: unless-stopped

volumes:
  mongo-data: