name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker-compose
        run: |
          docker-compose -f docker-compose.yaml build
      - name: Run docker-compose
        run: |
          docker-compose up -d mongodb backend frontend 
          sleep 10
      - name: Check health
        uses: thegabriele97/dockercompose-health-action@main
        with:
          timeout: '20'
          workdir: '.'