name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker-compose
        run: |
          cp server/.env .env
          docker-compose -f docker-compose.yaml build
      - name: Run docker-compose
        run: |
          docker-compose up mongodb backend frontend -d
          sleep 10
      - name: Run tests
        run: |
          curl http://localhost:8080
          curl http://localhost:27017
          curl http://localhost:8081