name: PEP8 Style Guide Enforcement

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Installation of testing utilities (Pylint)
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Style check (Run Pylint)
      run: |
        pylint $(git ls-files 'server/src/*.py')