name: Selenium test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build and up docker-compose
        run: |
          docker compose -f docker-compose.test.yaml up -d --build
          sleep 30
      - name: Run tests
        run: |
          docker compose exec node sh -c "npx mocha test.mjs"
